In [25]:
# dataset
from lerobot.datasets.lerobot_dataset import LeRobotDataset, LeRobotDatasetMetadata
import pandas as pd
import numpy as np
from pathlib import Path

In [9]:
# ugly hack
DATASETS_DIR = Path('/home/jonathan/Documents/Github/IDC_Project-Sim_Real_Sim/datasets')
HF_NAME = 'jonathm126'

In [10]:
REPO_NAME       = 'so101_car_pick_and_place'
EXPERIMENT_NAME = '50_episodes_v0'
DATASET_PATH    = DATASETS_DIR/REPO_NAME
DATASET_ID      = f"{HF_NAME}/{REPO_NAME}"

In [11]:
# select episodes
ds_meta= LeRobotDatasetMetadata(DATASET_ID, root = DATASET_PATH)
bad_eps = {}
episodes = [ep for ep in range(len(ds_meta.episodes)) if ep not in bad_eps]
ds = LeRobotDataset(repo_id = f"{HF_NAME}/{REPO_NAME}", root=f"{DATASETS_DIR}/{REPO_NAME}") # episodes=episodes,

#### Fix bad episodes

In [ ]:
episode_indices = list(ds.meta.episodes['videos/observation.images.top_cam/file_index'])
print(episode_indices)
len(ds.meta.episodes['meta/episodes/chunk_index'])

In [ ]:
dfmeta = pd.read_parquet('datasets/so101_car_pick_and_place/meta/episodes/chunk-000/file-000.parquet')
dfmeta.head(28)

In [ ]:
columns_to_check = [
    'videos/observation.images.wrist_cam/chunk_index',
    'videos/observation.images.wrist_cam/file_index',
    'videos/observation.images.top_cam/chunk_index',
    'videos/observation.images.top_cam/file_index'
]
dfmeta[columns_to_check] = dfmeta[columns_to_check].astype(int)

In [ ]:
dfmeta.to_parquet('datasets/so101_car_pick_and_place/meta/episodes/chunk-000/file-000.parquet', index=False)

In [ ]:
dfdata2 = pd.read_parquet('/home/jonathan/Github/IDC_Project-Sim_Real_Sim/datasets/so101_car_pick_and_place/data/chunk-000/file-000.parquet')
dfdata2.columns

#### Edit episode data

In [20]:
dfmeta = pd.read_parquet(ds.root.__str__() + '/meta/episodes/chunk-000/file-000.parquet')
dfmeta.head(10)

,episode_index,tasks,length,data/chunk_index,data/file_index,dataset_from_index,dataset_to_index,videos/observation.images.wrist_cam/chunk_index,videos/observation.images.wrist_cam/file_index,videos/observation.images.wrist_cam/from_timestamp,...,stats/index/mean,stats/index/std,stats/index/count,stats/task_index/min,stats/task_index/max,stats/task_index/mean,stats/task_index/std,stats/task_index/count,meta/episodes/chunk_index,meta/episodes/file_index
0,0,[Put the yellow car in the blue container],684,0,0,0,684,0,0,0.000000,...,[341.5],[197.453581042904],[684],[0],[0],[0.0],[0.0],[684],0,0
1,1,[Put the yellow car in the blue container],853,0,0,684,1537,0,0,22.800000,...,[1110.0],[246.23972059763227],[853],[0],[0],[0.0],[0.0],[853],0,0
2,2,[Put the yellow car in the blue container],632,0,0,1537,2169,0,0,51.233333,...,[1852.5],[182.44245668155207],[632],[0],[0],[0.0],[0.0],[632],0,0
3,3,[Put the yellow car in the blue container],619,0,0,2169,2788,0,0,72.300000,...,[2478.0],[178.68967513541457],[619],[0],[0],[0.0],[0.0],[619],0,0
4,4,[Put the yellow car in the blue container],748,0,0,2788,3536,0,0,92.933333,...,[3161.5],[215.92880771217165],[748],[0],[0],[0.0],[0.0],[748],0,0
5,5,[Put the yellow car in the blue container],873,0,0,3536,4409,0,0,117.866667,...,[3972.0],[252.01322716608877],[873],[0],[0],[0.0],[0.0],[873],0,0
6,6,[Put the yellow car in the blue container],873,0,0,4409,5282,0,0,146.966667,...,[4845.0],[252.01322716608877],[873],[0],[0],[0.0],[0.0],[873],0,0
7,7,[Put the yellow car in the blue container],626,0,0,5282,5908,0,0,176.066667,...,[5594.5],[180.710403685012],[626],[0],[0],[0.0],[0.0],[626],0,0
8,8,[Put the yellow car in the blue container],790,0,0,5908,6698,0,0,196.933333,...,[6302.5],[228.0531736240476],[790],[0],[0],[0.0],[0.0],[790],0,0
9,9,[Put the yellow car in the blue container],786,0,0,6698,7484,0,0,223.266667,...,[7090.5],[226.8984721558668],[786],[0],[0],[0.0],[0.0],[786],0,0

In [24]:
dfdata = pd.read_parquet(ds.root.__str__() +'/data/chunk-000/file-000.parquet')
dfdata.head(100)

,action,observation.state,timestamp,frame_index,episode_index,index,task_index,observation.environment_state
0,"[17.16946029663086, -98.8945541381836, 99.8184...","[16.767921447753906, -98.540771484375, 99.0863...",0.000000,0,0,0,0,"[409.6, 414.0, 156.54767]"
1,"[17.16946029663086, -98.8945541381836, 99.8184...","[16.767921447753906, -98.540771484375, 99.0863...",0.033333,1,0,1,0,"[409.6, 414.0, 156.54767]"
2,"[17.16946029663086, -98.8945541381836, 99.8184...","[16.767921447753906, -98.540771484375, 99.0863...",0.066667,2,0,2,0,"[409.6, 414.0, 156.54767]"
3,"[17.16946029663086, -98.8945541381836, 99.8184...","[16.767921447753906, -98.540771484375, 99.0863...",0.100000,3,0,3,0,"[409.6, 414.0, 156.54767]"
4,"[17.16946029663086, -98.8945541381836, 99.8184...","[16.767921447753906, -98.540771484375, 99.0863...",0.133333,4,0,4,0,"[409.6, 414.0, 156.54767]"
...,...,...,...,...,...,...,...,...
95,"[-1.5270018577575684, -97.2789077758789, 57.60...","[-1.7010935544967651, -98.4549331665039, 64.55...",3.166667,95,0,95,0,"[409.6, 414.0, 156.54767]"
96,"[-1.5270018577575684, -96.08843231201172, 56.0...","[-1.7010935544967651, -98.4549331665039, 63.63...",3.200000,96,0,96,0,"[409.6, 414.0, 156.54767]"
97,"[-1.5270018577575684, -94.38775634765625, 54.3...","[-1.5795868635177612, -98.28326416015625, 62.4...",3.233333,97,0,97,0,"[409.6, 414.0, 156.54767]"
98,"[-1.5270018577575684, -92.51700592041016, 52.6...","[-1.5795868635177612, -97.93991088867188, 61.1...",3.266667,98,0,98,0,"[409.6, 414.0, 156.54767]"
99,"[-1.5270018577575684, -90.30612182617188, 50.5...","[-1.7010935544967651, -97.33905792236328, 59.8...",3.300000,99,0,99,0,"[409.6, 414.0, 156.54767]"

In [28]:
arr = np.stack(dfdata['observation.environment_state'].values) 
maxs = np.array([640.0, 480.0, 360.0])
mins = np.array([0.0, 0.0, 0.0])
arr_norm = (arr - mins) / (maxs - mins)
dfdata_norm = dfdata.copy(deep=True)
dfdata_norm['observation.environment_state'] = list(arr_norm.astype(np.float32))

In [30]:
dfdata_norm.head(-10)

,action,observation.state,timestamp,frame_index,episode_index,index,task_index,observation.environment_state
0,"[17.16946029663086, -98.8945541381836, 99.8184...","[16.767921447753906, -98.540771484375, 99.0863...",0.000000,0,0,0,0,"[0.64, 0.8625, 0.43485463]"
1,"[17.16946029663086, -98.8945541381836, 99.8184...","[16.767921447753906, -98.540771484375, 99.0863...",0.033333,1,0,1,0,"[0.64, 0.8625, 0.43485463]"
2,"[17.16946029663086, -98.8945541381836, 99.8184...","[16.767921447753906, -98.540771484375, 99.0863...",0.066667,2,0,2,0,"[0.64, 0.8625, 0.43485463]"
3,"[17.16946029663086, -98.8945541381836, 99.8184...","[16.767921447753906, -98.540771484375, 99.0863...",0.100000,3,0,3,0,"[0.64, 0.8625, 0.43485463]"
4,"[17.16946029663086, -98.8945541381836, 99.8184...","[16.767921447753906, -98.540771484375, 99.0863...",0.133333,4,0,4,0,"[0.64, 0.8625, 0.43485463]"
...,...,...,...,...,...,...,...,...
36309,"[-6.815642356872559, -99.8299331665039, 97.276...","[-7.41190767288208, -99.39913940429688, 97.624...",27.200001,816,48,37710,0,"[0.712, 0.067, 0.5]"
36310,"[-6.815642356872559, -99.8299331665039, 97.276...","[-7.41190767288208, -99.39913940429688, 97.624...",27.233334,817,48,37711,0,"[0.712, 0.067, 0.5]"
36311,"[-6.741154670715332, -99.8299331665039, 97.276...","[-7.41190767288208, -99.39913940429688, 97.624...",27.266666,818,48,37712,0,"[0.712, 0.067, 0.5]"
36312,"[-6.741154670715332, -99.8299331665039, 97.276...","[-7.41190767288208, -99.39913940429688, 97.624...",27.299999,819,48,37713,0,"[0.712, 0.067, 0.5]"
36313,"[-6.741154670715332, -99.8299331665039, 97.276...","[-7.41190767288208, -99.39913940429688, 97.624...",27.333334,820,48,37714,0,"[0.712, 0.067, 0.5]"

In [31]:
dfdata_norm.to_parquet(ds.root.__str__() +'/data/chunk-000/file-000_1.parquet')